# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  test_on_node14:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install
        run: |
          npm install -save
          npm install -save-dev
      - name: npm test
        run: npm test
  test_on_node10:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: npm install
        run: |
          npm install -save
          npm install -save-dev
      - name: npm test
        run: npm test
  test_on_node8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '8'
      - name: npm install
        run: |
          npm install -save
          npm install -save-dev
      - name: npm test
        run: npm test
     
